<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\FrameFlow.Media\FrameFlow.Media.csproj" />
    <ProjectReference Include="..\FrameFlow.Playback\FrameFlow.Playback.csproj" />
    <ProjectReference Include="..\FrameFlow.Player\FrameFlow.Player.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.*" />
    <PackageReference
      Include="Microsoft.Extensions.DependencyInjection.Abstractions"
      Version="9.*"
    />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.*" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="FrameFlow.Graph" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FrameFlow.Graph/FrameFlow.Graph.csproj" />
  </ItemGroup>
</Project>
