<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="xunit" Version="2.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FrameFlow.Face\FrameFlow.Face.csproj" />
    <ProjectReference Include="..\..\src\FrameFlow.Video\FrameFlow.Video.csproj" />
    <ProjectReference Include="..\..\src\FrameFlow.Media\FrameFlow.Media.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FrameFlow.Graph" />
    <Using Include="FrameFlow.Media" />
    <Using Include="FrameFlow.Video" />
    <Using Include="FrameFlow.Face" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/FrameFlow.Graph/FrameFlow.Graph.csproj" />
  </ItemGroup>
</Project>
